-- Server-only metadata; no browser or public key may read backup records.
create table if not exists public.backup_runs (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id),
  request_key text not null,
  status text not null check (status in ('running','complete','failed','expired')),
  created_at timestamptz not null default now(),
  verified_at timestamptz,
  expired_at timestamptz,
  storage_path text,
  size_bytes bigint not null default 0 check (size_bytes>=0),
  file_count integer not null default 0 check (file_count>=0),
  sha256 text,
  error_code text,
  unique (organization_id,request_key),
  check (status <> 'complete' or (verified_at is not null and storage_path is not null and sha256 ~ '^[a-f0-9]{64}$'))
);
alter table public.backup_runs enable row level security;
revoke all on public.backup_runs from anon,authenticated;
grant select,insert,update on public.backup_runs to service_role;
grant usage,select on sequence public.backup_runs_id_seq to service_role;
create index if not exists backup_runs_org_status on public.backup_runs(organization_id,status,id desc);

-- One statement gives a consistent organisation snapshot and avoids REST row limits.
create or replace function public.werkstuur_export_organization(p_organization_id bigint,p_app_version text)
returns jsonb language sql stable security invoker set search_path=public,pg_temp as $snapshot$
  select jsonb_build_object(
    'meta',jsonb_build_object('app_name','Werkstuur','app_version',p_app_version,'exported_at',now(),
      'contains_passwords',false,'contains_attachment_bytes',false,'organization_id',p_organization_id),
    'organization',(select to_jsonb(o) from public.organizations o where o.id=p_organization_id),
    'settings',coalesce((select jsonb_agg(jsonb_build_object('key',r.key,'value',r.value) order by r.key) from public.organization_settings r where r.organization_id=p_organization_id),'[]'::jsonb),
    'users',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'email',r.email,'display_name',r.display_name,'role',r.role,'active',r.active,'created_at',r.created_at) order by r.id) from public.users r where r.organization_id=p_organization_id),'[]'::jsonb),
    'customers',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.customer_records r where r.organization_id=p_organization_id),'[]'::jsonb),
    'support_tickets',coalesce((select jsonb_agg(to_jsonb(r)-'request_key'-'fingerprint' order by r.id) from public.support_tickets r where r.organization_id=p_organization_id),'[]'::jsonb),
    'support_access_requests',coalesce((select jsonb_agg(to_jsonb(r)-'request_key' order by r.id) from public.support_access_requests r where r.organization_id=p_organization_id),'[]'::jsonb),
    'support_access_events',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.support_access_events r where r.organization_id=p_organization_id),'[]'::jsonb),
    'pilots',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.pilots r where r.organization_id=p_organization_id),'[]'::jsonb),
    'pilot_snapshots',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.pilot_snapshots r where r.organization_id=p_organization_id),'[]'::jsonb),
    'cases',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.cases r where r.organization_id=p_organization_id),'[]'::jsonb),
    'notes',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.notes r where r.organization_id=p_organization_id),'[]'::jsonb),
    'attachments',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.attachments r where r.organization_id=p_organization_id),'[]'::jsonb),
    'audit',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.audit r where r.organization_id=p_organization_id),'[]'::jsonb)
  );
$snapshot$;
revoke all on function public.werkstuur_export_organization(bigint,text) from public,anon,authenticated;
grant execute on function public.werkstuur_export_organization(bigint,text) to service_role;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('werkstuur-backups','werkstuur-backups',false,33554432,array['application/zip'])
on conflict(id) do update set public=false,file_size_limit=33554432,allowed_mime_types=array['application/zip'];

create or replace function public.werkstuur_backup_usage()
returns jsonb language sql stable security invoker set search_path=public,pg_temp as $usage$
  select jsonb_build_object('total_bytes',coalesce(sum((metadata->>'size')::bigint),0),
    'backup_bytes',coalesce(sum((metadata->>'size')::bigint) filter(where bucket_id='werkstuur-backups'),0))
  from storage.objects;
$usage$;
revoke all on function public.werkstuur_backup_usage() from public,anon,authenticated;
grant execute on function public.werkstuur_backup_usage() to service_role;
