-- Run once through a tracked Supabase migration. Custom auth stays server-only.
create table public.support_access_requests (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id),
  requester_id bigint not null references public.users(id),
  reason text not null check (length(btrim(reason)) between 10 and 1000),
  scope text not null default 'workspace_read' check (scope = 'workspace_read'),
  requested_minutes integer not null check (requested_minutes in (15,30,60)),
  approved_minutes integer check (approved_minutes in (15,30,60) and approved_minutes <= requested_minutes),
  status text not null default 'pending' check (status in ('pending','approved','rejected','revoked','cancelled','expired')),
  request_key text not null check (request_key ~ '^[A-Za-z0-9-]{16,80}$'),
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  request_expires_at timestamptz not null default (now() + interval '24 hours'),
  decided_by bigint,
  decided_at timestamptz,
  expires_at timestamptz,
  ended_by bigint references public.users(id),
  ended_at timestamptz,
  unique (requester_id,request_key),
  unique (id,organization_id,requester_id),
  foreign key (decided_by,organization_id) references public.users(id,organization_id),
  check (request_expires_at > created_at and request_expires_at <= created_at + interval '24 hours'),
  check (status <> 'approved' or (decided_by is not null and decided_at is not null and expires_at is not null and approved_minutes is not null
    and expires_at = decided_at + make_interval(mins => approved_minutes)))
);
create unique index support_access_one_open on public.support_access_requests(organization_id,requester_id)
  where status in ('pending','approved');
create index support_access_requester on public.support_access_requests(requester_id,id desc);
create index support_access_decider on public.support_access_requests(decided_by,organization_id);
create index support_access_ender on public.support_access_requests(ended_by);
alter table public.support_access_requests enable row level security;
revoke all on public.support_access_requests from public,anon,authenticated,service_role;
grant select,insert,update on public.support_access_requests to service_role;
grant usage,select on sequence public.support_access_requests_id_seq to service_role;
revoke all on sequence public.support_access_requests_id_seq from public,anon,authenticated;

-- Separate append-only history: a foreign support actor cannot use audit's member FK.
create table public.support_access_events (
  id bigint generated by default as identity primary key,
  request_id bigint not null,
  organization_id bigint not null,
  requester_id bigint not null,
  actor_id bigint not null references public.users(id),
  actor_name text not null,
  action text not null check (action in ('requested','approved','rejected','revoked','cancelled','expired','opened','left')),
  created_at timestamptz not null default now(),
  detail jsonb not null default '{}'::jsonb,
  foreign key (request_id,organization_id,requester_id) references public.support_access_requests(id,organization_id,requester_id)
);
create index support_access_events_org on public.support_access_events(organization_id,id desc);
create index support_access_events_requester on public.support_access_events(requester_id,id desc);
create index support_access_events_actor on public.support_access_events(actor_id);
create index support_access_events_request on public.support_access_events(request_id,organization_id,requester_id);
alter table public.support_access_events enable row level security;
revoke all on public.support_access_events from public,anon,authenticated,service_role;
grant select,insert on public.support_access_events to service_role;
grant usage,select on sequence public.support_access_events_id_seq to service_role;
revoke all on sequence public.support_access_events_id_seq from public,anon,authenticated;

create function public.werkstuur_support_access_check(p_actor_id bigint,p_organization_id bigint)
returns jsonb language sql stable security invoker set search_path='' as $check$
  select jsonb_build_object('grant', (
    select jsonb_build_object('id',r.id,'organization_id',r.organization_id,'scope',r.scope,
      'expires_at',r.expires_at,'approved_minutes',r.approved_minutes,'approved_by',a.display_name)
    from public.support_access_requests r
    join public.users u on u.id=r.requester_id and u.active and u.is_platform_owner
    join public.users a on a.id=r.decided_by and a.organization_id=r.organization_id
      and a.active and a.role='admin' and not a.is_platform_owner
    join public.organizations o on o.id=r.organization_id and o.status not in ('suspended','archived')
    where r.requester_id=p_actor_id and r.organization_id=p_organization_id
      and u.organization_id <> r.organization_id and r.status='approved' and r.expires_at > now()
    order by r.id desc limit 1
  ));
$check$;
revoke all on function public.werkstuur_support_access_check(bigint,bigint) from public,anon,authenticated;
grant execute on function public.werkstuur_support_access_check(bigint,bigint) to service_role;

create function public.werkstuur_support_access_change(
  p_actor_id bigint,p_action text,p_organization_id bigint default null,p_request_id bigint default null,
  p_version integer default null,p_reason text default '',p_duration_minutes integer default 60,p_request_key text default '')
returns jsonb language plpgsql security invoker set search_path='' as $change$
declare
  actor public.users%rowtype;
  org public.organizations%rowtype;
  request public.support_access_requests%rowtype;
  old_request public.support_access_requests%rowtype;
  event_action text;
begin
  select * into actor from public.users where id=p_actor_id and active;
  if not found then return jsonb_build_object('error','Geen geldig account.','http_status',403,'code','forbidden'); end if;
  if p_action='request' then
    if not actor.is_platform_owner then return jsonb_build_object('error','Alleen de Werkstuur-eigenaar kan toegang aanvragen.','http_status',403,'code','forbidden'); end if;
    select * into org from public.organizations where id=p_organization_id;
    if not found or org.id=actor.organization_id or org.status in ('suspended','archived') then
      return jsonb_build_object('error','Deze organisatie kan geen inzageverzoek ontvangen.','http_status',409,'code','organization_unavailable');
    end if;
    if not exists (select 1 from public.users where organization_id=org.id and active and role='admin' and not is_platform_owner) then
      return jsonb_build_object('error','Dit bedrijf heeft eerst een eigen actieve bedrijfsbeheerder nodig.','http_status',409,'code','company_admin_required');
    end if;
    if length(btrim(p_reason)) not between 10 and 1000 or p_duration_minutes not in (15,30,60)
       or p_request_key !~ '^[A-Za-z0-9-]{16,80}$' then
      return jsonb_build_object('error','Ongeldig toestemmingsverzoek.','http_status',400,'code','invalid_request');
    end if;
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('werkstuur-support:' || actor.id || ':' || org.id,0));
    select * into request from public.support_access_requests where requester_id=actor.id and request_key=p_request_key;
    if found then
      if request.organization_id<>org.id or request.reason<>btrim(p_reason) or request.requested_minutes<>p_duration_minutes then
        return jsonb_build_object('error','Deze aanvraagcode hoort bij een ander verzoek.','http_status',409,'code','request_key_conflict');
      end if;
      return jsonb_build_object('request',to_jsonb(request)-'request_key','created',false);
    end if;
    for old_request in select * from public.support_access_requests
      where requester_id=actor.id and organization_id=org.id and status in ('pending','approved') for update
    loop
      if (old_request.status='pending' and old_request.request_expires_at>now())
        or (old_request.status='approved' and (public.werkstuur_support_access_check(actor.id,org.id)->'grant') <> 'null'::jsonb) then
        return jsonb_build_object('error','Er is al een open verzoek of actieve toestemming.','http_status',409,'code','request_already_open');
      end if;
      update public.support_access_requests set status='expired',ended_at=now(),version=version+1 where id=old_request.id;
      insert into public.support_access_events(request_id,organization_id,requester_id,actor_id,actor_name,action)
        values(old_request.id,org.id,actor.id,actor.id,actor.display_name,'expired');
    end loop;
    insert into public.support_access_requests(organization_id,requester_id,reason,requested_minutes,request_key)
      values(org.id,actor.id,btrim(p_reason),p_duration_minutes,p_request_key) returning * into request;
    event_action := 'requested';
  else
    select * into request from public.support_access_requests where id=p_request_id for update;
    if not found then return jsonb_build_object('error','Verzoek niet gevonden.','http_status',404,'code','not_found'); end if;
    if p_action='cancel' then
      if not actor.is_platform_owner or actor.id<>request.requester_id then
        return jsonb_build_object('error','Verzoek niet gevonden.','http_status',404,'code','not_found');
      end if;
    elsif p_action in ('approve','reject','revoke') then
      if actor.is_platform_owner or actor.role<>'admin' or actor.organization_id<>request.organization_id then
        return jsonb_build_object('error','Alleen de eigen bedrijfsbeheerder kan dit besluit nemen.','http_status',403,'code','forbidden');
      end if;
    else return jsonb_build_object('error','Ongeldig besluit.','http_status',400,'code','invalid_request'); end if;
    if p_version is null or p_version<>request.version then
      return jsonb_build_object('error','Dit verzoek is intussen gewijzigd. Vernieuw het overzicht.','http_status',409,'code','version_conflict');
    end if;
    if p_action in ('approve','reject') and (request.status<>'pending' or request.request_expires_at<=now()) then
      return jsonb_build_object('error','Dit verzoek staat niet meer open.','http_status',409,'code','request_closed');
    elsif p_action='revoke' and request.status<>'approved' then
      return jsonb_build_object('error','Deze toestemming is niet actief.','http_status',409,'code','request_closed');
    elsif p_action='cancel' and request.status not in ('pending','approved') then
      return jsonb_build_object('error','Dit verzoek is al gesloten.','http_status',409,'code','request_closed');
    end if;
    if p_action='approve' then
      select * into org from public.organizations where id=request.organization_id;
      if org.status in ('suspended','archived') or not exists (select 1 from public.users where id=request.requester_id and active and is_platform_owner and organization_id<>org.id) then
        return jsonb_build_object('error','De organisatie of aanvrager is niet beschikbaar.','http_status',409,'code','organization_unavailable');
      end if;
      if p_duration_minutes not in (15,30,60) or p_duration_minutes>request.requested_minutes then
        return jsonb_build_object('error','De goedgekeurde duur mag niet langer zijn dan aangevraagd.','http_status',400,'code','invalid_request');
      end if;
      update public.support_access_requests set status='approved',approved_minutes=p_duration_minutes,
        decided_by=actor.id,decided_at=now(),expires_at=now()+make_interval(mins => p_duration_minutes),version=version+1
        where id=request.id returning * into request;
      event_action := 'approved';
    elsif p_action='reject' then
      update public.support_access_requests set status='rejected',decided_by=actor.id,decided_at=now(),version=version+1
        where id=request.id returning * into request;
      event_action := 'rejected';
    else
      event_action := case when p_action='revoke' then 'revoked' else 'cancelled' end;
      update public.support_access_requests set status=event_action,ended_by=actor.id,ended_at=now(),version=version+1
        where id=request.id returning * into request;
      -- Keep the foreign context until explicit recovery: its next read must fail
      -- rather than returning home-company data under a stale customer heading.
    end if;
  end if;
  insert into public.support_access_events(request_id,organization_id,requester_id,actor_id,actor_name,action,detail)
    values(request.id,request.organization_id,request.requester_id,actor.id,actor.display_name,event_action,
      jsonb_build_object('version',request.version,'scope',request.scope,'expires_at',request.expires_at));
  return jsonb_build_object('request',to_jsonb(request)-'request_key','created',p_action='request');
end;
$change$;
revoke all on function public.werkstuur_support_access_change(bigint,text,bigint,bigint,integer,text,integer,text) from public,anon,authenticated;
grant execute on function public.werkstuur_support_access_change(bigint,text,bigint,bigint,integer,text,integer,text) to service_role;

create function public.werkstuur_support_context(p_actor_id bigint,p_session_hash text,p_organization_id bigint)
returns jsonb language plpgsql security invoker set search_path='' as $context$
declare actor public.users%rowtype; org public.organizations%rowtype; request public.support_access_requests%rowtype; previous_org bigint;
begin
  select * into actor from public.users where id=p_actor_id and active and is_platform_owner;
  if not found then return jsonb_build_object('error','Geen eigenaarstoegang.','http_status',403,'code','forbidden'); end if;
  select active_organization_id into previous_org from public.sessions
    where user_id=actor.id and token_hash=p_session_hash and expires_at>now() for update;
  if not found then return jsonb_build_object('error','Je sessie is verlopen.','http_status',401,'code','unauthorized'); end if;
  select * into org from public.organizations where id=p_organization_id;
  if not found then return jsonb_build_object('error','Organisatie niet gevonden.','http_status',404,'code','not_found'); end if;
  if org.id<>actor.organization_id then
    select * into request from public.support_access_requests where requester_id=actor.id
      and organization_id=org.id and status='approved' and expires_at>now() for share;
    if not found or (public.werkstuur_support_access_check(actor.id,org.id)->'grant')='null'::jsonb then
      return jsonb_build_object('error','De bedrijfsbeheerder moet eerst toestemming geven voor tijdelijke inzage.','http_status',403,'code','support_access_required');
    end if;
    if previous_org is distinct from org.id then
      insert into public.support_access_events(request_id,organization_id,requester_id,actor_id,actor_name,action)
        values(request.id,org.id,actor.id,actor.id,actor.display_name,'opened');
    end if;
  elsif previous_org is distinct from actor.organization_id then
    select * into request from public.support_access_requests where requester_id=actor.id and organization_id=previous_org order by id desc limit 1;
    if found then insert into public.support_access_events(request_id,organization_id,requester_id,actor_id,actor_name,action)
      values(request.id,previous_org,actor.id,actor.id,actor.display_name,'left'); end if;
  end if;
  update public.sessions set active_organization_id=org.id where user_id=actor.id and token_hash=p_session_hash;
  return jsonb_build_object('ok',true,'organization',to_jsonb(org));
end;
$context$;
revoke all on function public.werkstuur_support_context(bigint,text,bigint) from public,anon,authenticated;
grant execute on function public.werkstuur_support_context(bigint,text,bigint) to service_role;

-- Back up the consent journal as history; restoration never reactivates grants.
create or replace function public.werkstuur_export_organization(p_organization_id bigint,p_app_version text)
returns jsonb language sql stable security invoker set search_path=public,pg_temp as $snapshot$
  select jsonb_build_object(
    'meta',jsonb_build_object('app_name','Werkstuur','app_version',p_app_version,'exported_at',now(),
      'contains_passwords',false,'contains_attachment_bytes',false,'organization_id',p_organization_id),
    'organization',(select to_jsonb(o) from public.organizations o where o.id=p_organization_id),
    'settings',coalesce((select jsonb_agg(jsonb_build_object('key',r.key,'value',r.value) order by r.key) from public.organization_settings r where r.organization_id=p_organization_id),'[]'::jsonb),
    'users',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'email',r.email,'display_name',r.display_name,'role',r.role,'active',r.active,'created_at',r.created_at) order by r.id) from public.users r where r.organization_id=p_organization_id),'[]'::jsonb),
    'customers',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.customer_records r where r.organization_id=p_organization_id),'[]'::jsonb),
    'support_tickets',coalesce((select jsonb_agg(to_jsonb(r)-'request_key'-'fingerprint' order by r.id) from public.support_tickets r where r.organization_id=p_organization_id),'[]'::jsonb),
    'support_access_requests',coalesce((select jsonb_agg(to_jsonb(r)-array['request_key','code_nonce','code_hash','activated_session_hash'] order by r.id) from public.support_access_requests r where r.organization_id=p_organization_id),'[]'::jsonb),
    'support_access_events',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.support_access_events r where r.organization_id=p_organization_id),'[]'::jsonb),
    'pilots',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.pilots r where r.organization_id=p_organization_id),'[]'::jsonb),
    'pilot_snapshots',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.pilot_snapshots r where r.organization_id=p_organization_id),'[]'::jsonb),
    'cases',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.cases r where r.organization_id=p_organization_id),'[]'::jsonb),
    'notes',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.notes r where r.organization_id=p_organization_id),'[]'::jsonb),
    'attachments',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.attachments r where r.organization_id=p_organization_id),'[]'::jsonb),
    'audit',coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from public.audit r where r.organization_id=p_organization_id),'[]'::jsonb)
  );
$snapshot$;
revoke all on function public.werkstuur_export_organization(bigint,text) from public,anon,authenticated;
grant execute on function public.werkstuur_export_organization(bigint,text) to service_role;
