"use strict";
const fs=require("fs"),vm=require("vm"),assert=require("assert");
let passed=0;const check=(name,fn)=>{fn();passed++;process.stdout.write("PASS "+name+"\n")};
function segment(file,start,end){const s=fs.readFileSync(file,"utf8"),i=s.indexOf(start),j=s.indexOf(end,i+start.length);assert(i>=0&&j>i);return s.slice(i,j)}
const nodes=new Map();function node(id){if(!nodes.has(id))nodes.set(id,{textContent:"",value:"",focused:false,attrs:{},classes:new Set(),classList:{toggle(name,force){if(force)nodes.get(id).classes.add(name);else nodes.get(id).classes.delete(name)},remove(name){nodes.get(id).classes.delete(name)},add(name){nodes.get(id).classes.add(name)}},setAttribute(k,v){this.attrs[k]=v},focus(){this.focused=true},checkValidity(){return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(this.value)}});return nodes.get(id)}
let writable=false,shown=[],apiCalls=0;
const ctx={console,ownerOrganizations:[],me:{role:"admin",is_platform_owner:true,organization_id:2,base_organization_id:1,organization_name:"TEST Klantbedrijf"},settings:{},$:node,caseWriteAllowed:()=>writable,document:{body:{dataset:{}},querySelector:node},show:v=>{shown.push(v);return true},api:async()=>{apiCalls++},wsConfirmLeave:()=>true,escapeReport:x=>String(x??"").replace(/[<>&"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;"})[c]),escAttr:x=>ctx.escapeReport(x),wsIcon:()=>"",emptyState:(title,message)=>title+" "+message};vm.createContext(ctx);
vm.runInContext(segment("app.js","function caseForDisplay(","async function loadCases("),ctx);
vm.runInContext(segment("command-v210.js","function customerWriteAllowed(","async function loadPlatform("),ctx);
vm.runInContext(segment("app.js","async function switchOrganization(","async function toggleOrganization("),ctx);
vm.runInContext(segment("app.js","function analysisSummary(","function collectCaseAnalysis("),ctx);
check("Active customer stays visible through owner management and can return",()=>{ctx.configureRoleNavigation("beheer");assert.equal(node("workspaceName").textContent,"TEST Klantbedrijf");assert.equal(node("workspacePlan").textContent,"SUPPORTINZAGE");assert(!node(".cc-nav-main").classes.has("hidden"));assert(!node("workspaceReturn").classes.has("hidden"));assert(!node("ownerContextBanner").classes.has("hidden"));assert.equal(ctx.document.title,"Werkstuur · TEST Klantbedrijf")});
check("Returning to the current workspace avoids switching sessions or data",()=>{ctx.switchOrganization(2);assert.equal(shown.at(-1),"dashboard");assert.equal(apiCalls,0)});
check("Internal owner retains software controls",()=>{writable=true;ctx.me.organization_id=1;ctx.configureRoleNavigation("platform");assert.equal(node("workspaceName").textContent,"Werkstuur Control");assert(node(".cc-nav-main").classes.has("hidden"));assert(node("workspaceReturn").classes.has("hidden"));assert(node("ownerContextBanner").classes.has("hidden"))});
check("Unavailable analysis cannot present legacy score, route or parts as current",()=>{const old={id:7,type:"Old",score:82,dispatch:"Old advice",prep:["Old parts"],fault_confidence:"hoog",analysis:{unavailable:true}};const shown=ctx.caseForDisplay(old);assert.equal(shown.score,null);assert.equal(ctx.caseScoreLabel(shown),"Te beoordelen");assert(!shown.dispatch.includes("Old advice"));assert.equal(shown.prep.length,0);assert.equal(shown.fault_confidence,"Niet beoordeeld");assert.equal(old.score,82)});
check("A planner can repair legacy input while support owner cannot edit",()=>{ctx.me.role="planner";writable=true;const c={type:"Oud type",problem:"<script>",manufacturer:"Test",analysis:{unavailable:true}};let html=ctx.renderCaseAnalysis(c);assert(html.includes('id="analysisType"'));assert(html.includes('Kies een ondersteund type'));assert(html.includes("&lt;script&gt;"));writable=false;assert(!ctx.renderCaseAnalysis(c).includes('id="caseAnalysisForm"'))});
const intake={byId:node,showError:(id,msg)=>{node(id).textContent=msg},customer:node("customer"),city:node("city"),phone:node("phone"),email:node("email"),type:node("type"),manufacturer:node("manufacturer"),problem:node("problem")};vm.createContext(intake);
vm.runInContext(segment("intake.html","function validateStep(","function nextStep("),intake);
vm.runInContext(segment("intake-ui-v200.js","validateStep=((original)","setStep=((original)"),intake);
node("customer").value="TEST Klant";node("city").value="Testplaats";
check("Intake without contact stops, marks both fields and focuses phone",()=>{assert.equal(intake.validateStep(1),false);assert.equal(node("phone").attrs["aria-invalid"],"true");assert.equal(node("email").attrs["aria-invalid"],"true");assert(node("phone").focused)});
check("Malformed email and unusable phone cannot bypass the step",()=>{node("email").value="bad-email";assert.equal(intake.validateStep(1),false);node("email").value="good@test.invalid";node("phone").value="123";assert.equal(intake.validateStep(1),false)});
check("Email-only and international phone-only clear previous field errors",()=>{node("phone").value="";assert.equal(intake.validateStep(1),true);assert.equal(node("phone").attrs["aria-invalid"],"false");node("email").value="";node("phone").value="+31 (0)6 1234 5678";assert.equal(intake.validateStep(1),true)});
process.stdout.write(JSON.stringify({passed,total:passed,mode:"actual UI functions with isolated DOM fixture"})+"\n");
